<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-K1IJUS5" failures="1" tests="7" name="Test" time="6.977" errors="0" timestamp="2024-07-26T09:58:51 EDT">
  <testcase classname="com.github.tests.CRUD.ValidateGetAddUpdateDeleteData" name="validateGetSingleRepo" time="2.02"/>
  <testcase classname="com.github.tests.CRUD.ValidateGetAddUpdateDeleteData" name="validateGetAllRepo" time="1.412"/>
  <testcase classname="com.github.tests.CRUD.ValidateGetAddUpdateDeleteData" name="validatInvalidSingleRepo" time="0.146"/>
  <testcase classname="com.github.tests.CRUD.ValidateGetAddUpdateDeleteData" name="validateAddDataFunctionality" time="0.824"/>
  <testcase classname="com.github.tests.CRUD.ValidateGetAddUpdateDeleteData" name="validateAddInvalidDataFunctionality" time="1.337"/>
  <testcase classname="com.github.tests.CRUD.ValidateGetAddUpdateDeleteData" name="validateUpdateDataFunctionality" time="0.227">
    <failure type="java.lang.AssertionError" message="Update data functionality is not working as expected. expected [200] but found [307]">
      <![CDATA[java.lang.AssertionError: Update data functionality is not working as expected. expected [200] but found [307]
at com.github.tests.CRUD.ValidateGetAddUpdateDeleteData.validateUpdateDataFunctionality(ValidateGetAddUpdateDeleteData.java:127)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validateUpdateDataFunctionality -->
  <testcase classname="com.github.tests.CRUD.ValidateGetAddUpdateDeleteData" name="validateDeleteRepo" time="0.137"/>
</testsuite> <!-- Test -->
